### ISSUE TITLE
Overlapping button

### ISSUE THREAD

**Issue by ricetech** [swestwood/karel-helper-public#1]
![image](https://user-images.githubusercontent.com/39015447/79302152-81cd8200-7eb9-11ea-82ef-a3fde9931860.png)

**Comment by swestwood** [comment]
Weird! I just tweaked that area as part of a larger change so they show up next to each other instead -- can you reopen if you still see issues? 
![image](https://user-images.githubusercontent.com/748149/79305618-948b8b00-7ea8-11ea-9677-7078070faed6.png)

**Comment by ricetech** [comment]
Just checked again, it's working now!
![image](https://user-images.githubusercontent.com/39015447/79310751-6fa80f80-7eca-11ea-896e-53fd64b59e9d.png)
